In [1]:
import numpy as np
import pandas as pd

#矩阵乘法
a=np.array([2,3,4])
b=np.array([3,4,5])
vector=np.dot(a,b)
vector

38

In [7]:
#转置
arr=np.array([5,15,20,30]).reshape(4,1)
arr



SyntaxError: invalid syntax (<ipython-input-7-9e1570e10c95>, line 5)

In [3]:
#矩阵的另外一种表示
np.matrix([1,2,3,4])

matrix([[1, 2, 3, 4]])

In [10]:
#使用arange创建矩阵
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
#矩阵点乘用*号
#矩阵乘法用np.dot()
#矩阵转置函数
arr1=np.transpose(arr)
arr1

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [13]:
#方阵存在逆矩阵
arr=[[1,2],[3,4]]
arr_inv=np.linalg.inv(arr)
arr_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
np.dot(arr,arr_inv)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [15]:
#设置精度
np.set_printoptions(suppress=True)
np.dot(arr,arr_inv)

array([[1., 0.],
       [0., 1.]])

In [16]:
#取对角元素
np.diag(arr)

array([1, 4])

In [17]:
#矩阵解方程
#方程
A=np.array([[1,2],[2,3]])
A

array([[1, 2],
       [2, 3]])

In [20]:
#值
b=np.array([3,5])
b

array([3, 5])

In [21]:
X=np.linalg.solve(A,b)
X

array([1., 1.])

In [23]:
np.dot(A,X)

array([3., 5.])

In [4]:
import numpy as np
#读取文件txt或者csv
#data=np.genfromtxt('',delimiter=',',skip_header=1)
#data=np.loadtxt('')
#查看函数参数
np.genfromtxt?
#fmt存储格式
#np.savetxt('',data,delimiter,fmt)
np.savetxt?

In [7]:
#字符串操作
str=[chr(ord('a')+i) for i in range(5)]
str1=[i.upper() for i in str]
str1

['A', 'B', 'C', 'D', 'E']

In [8]:
#大小写
str2=np.char.upper(str)
str2

array(['A', 'B', 'C', 'D', 'E'], dtype='<U1')

In [16]:
#拼接
str3=[chr(ord('e')+i) for i in range(5)]
str4=np.char.add(str1,str3)
str4
#乘积
str5=np.char.multiply(['中国'],3)
str5
#拼接
str6=np.char.join(['-'],['hello','world'])
str6
#替换
str7=np.char.replace(str5,'中国','china')
str7
#去除
str8=np.char.strip(str6,'-')
str8

array(['h-e-l-l-o', 'w-o-r-l-d'], dtype='<U9')